### PR TITLE
Fit my needs

### PR DESCRIPTION
**Pull request by GertjanReynaert**
- [x] export messages in js files instead of json files
- [x] export messages into a single folder instead of nested folder structure
- [ ] export messages into a single file
- [ ] check to be exported messages against existing translation file

### CODE REVIEW

**Comment by izziaraffaele** [comment]
Good stuff man! Would be nice if you could integrate your changes with a configuration parameter so people can decide on their own the output format (json,js), the folder structure etc...

For example I like json and I would like to have 1 folder with files split by component.

**Comment by GertjanReynaert** [comment]
@izziaraffaele thx, I think instead of continueing on this branch, I will just start making small contributions to the original plugin, with just an option per feature I add.

**Comment by izziaraffaele** [comment]
that's is what I wanted to say :) GJ anyways and let me know if you need help

**Comment by GertjanReynaert** [comment]
I'll close this pr, and delete this branch, since I won't be continuing here.
In case you're interested: here is the pr for the js output: https://github.com/yahoo/babel-plugin-react-intl/pull/12

**Comment by ericf** [comment]
Here's my thoughts on this list of changes and why I designed the Babel plugin the way it is today: https://github.com/yahoo/babel-plugin-react-intl/pull/12#issuecomment-150651180

**Pull request closed without merging**
